# automation.yaml（整理版）
# 更新時間：20250625_1555
# 分類說明如下：
# 01- 出門 / 回家 相關（含掃地機器人、SSID、除濕機）
# 02- 洗澡 / 暖風機控制
# 03- 除濕機水滿提醒與解除
# 04- 除濕機自動控制（出門 / 回家）
# 05- 臥室燈光（夜間 / 半夜）
# 
# 所有自動化皆已依照功能區分類別與編號，方便後續管理。

# 01- 出門 / 回家 相關（含掃地機器人、SSID、除濕機）
- id: auto_01_go_out_both_away_with_door
  alias: 出門：兩人離家且門有開過（含第一次出門掃地）
  mode: single
  trigger:
    - platform: state
      entity_id:
        - device_tracker.amber_s_iphone
        - device_tracker.iphone
      to: not_home
      for: "00:01:00"
  condition:
    - condition: state
      entity_id: device_tracker.amber_s_iphone
      state: not_home
    - condition: state
      entity_id: device_tracker.iphone
      state: not_home
    - condition: state
      entity_id: input_boolean.door_opened_recently
      state: "on"
  action:
    - variables:
        last_go_out: "{{ states('input_datetime.last_go_out_time') }}"
        today: "{{ now().date() }}"
        last_date: "{{ as_datetime(last_go_out).date() if last_go_out not in ['unknown', 'unavailable'] else today - timedelta(days=1) }}"
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ last_date != today }}"
          sequence:
            - service: button.press
              target:
                entity_id: button.roborock_s8_maxv_ultra_ke_ting_ci_wo
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.last_go_out_time
      data:
        datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.go_out_mode
    - delay: "00:00:02"
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.go_out_mode

- id: auto_02_door_open_record
  alias: 大門開啟紀錄（10分鐘內有效）
  trigger:
    - platform: state
      entity_id: binary_sensor.door_entry
      to: "on"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.door_opened_recently
    - delay: "00:10:00"
    - service: input_boolean.turn_off
      entity_id: input_boolean.door_opened_recently

- id: auto_03_come_home_ssid
  alias: 回家（任一人回家）
  trigger:
    - platform: state
      entity_id:
        - sensor.amber_s_iphone_ssid
        - sensor.iphone_ssid
      to: "RS300"
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ states('sensor.amber_s_iphone_ssid') == 'RS300' }}"
        - condition: template
          value_template: "{{ states('sensor.iphone_ssid') == 'RS300' }}"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.go_out_mode
    - service: notify.mobile_app_amber_s_iphone
      data:
        message: "有人回家了～（除濕機記得看一下）"

- id: auto_04_come_home_device_tracker
  alias: 回家：任一人回家
  trigger:
    - platform: state
      entity_id:
        - device_tracker.amber_s_iphone
        - device_tracker.iphone
      to: home
  condition:
    - condition: state
      entity_id: input_boolean.come_home_mode
      state: "off"
    - condition: or
      conditions:
        - condition: state
          entity_id: device_tracker.amber_s_iphone
          state: home
        - condition: state
          entity_id: device_tracker.iphone
          state: home
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.come_home_mode
    - delay: "00:00:02"
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.come_home_mode
    - choose:
        - conditions:
            - condition: or
              conditions:
                - condition: state
                  entity_id: input_boolean.water_full_livingroom
                  state: "on"
                - condition: state
                  entity_id: input_boolean.water_full_bedroom
                  state: "on"
                - condition: state
                  entity_id: input_boolean.water_full_bedroom2
                  state: "on"
          sequence:
            - variables:
                msg: >-
                  {% set msg_list = [] %}
                  {% if is_state('input_boolean.water_full_livingroom', 'on') %}
                    {% set _ = msg_list.append('客廳除濕機') %}
                  {% endif %}
                  {% if is_state('input_boolean.water_full_bedroom', 'on') %}
                    {% set _ = msg_list.append('主臥除濕機') %}
                  {% endif %}
                  {% if is_state('input_boolean.water_full_bedroom2', 'on') %}
                    {% set _ = msg_list.append('次臥除濕機') %}
                  {% endif %}
                  {{ msg_list | join('、') ~ '可能已滿水，請確認是否需要倒水。' }}
            - service: tts.google_translate_say
              data:
                entity_id: media_player.ke_ting
                message: "{{ msg }}"
